export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_REQUEST = `${FORGOT_PASSWORD}/FORGOT_PASSWORD_REQUEST`;
export const FORGOT_PASSWORD_SEND_STATUS = `${FORGOT_PASSWORD}/FORGOT_PASSWORD_SEND_STATUS`;
export const SENT = `SENT`;
export const NOT_SEND = `NOT_SEND`;
