export const API_URL = "forget-password/sms";
export const API_CHANGE_PASSWORD_URL = "forget-password/reset/sms";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_REQUEST = `${FORGOT_PASSWORD}/FORGOT_PASSWORD_REQUEST`;
export const FORGOT_NEW_PASSWORD_REQUEST = `${FORGOT_PASSWORD}/FORGOT_NEW_PASSWORD_REQUEST`;
export const FORGOT_PASSWORD_VIEW_STATUS = `${FORGOT_PASSWORD}/FORGOT_PASSWORD_VIEW_STATUS`;

export const FORGOT_PASSWORD_VIEW = `FORGOT_PASSWORD_VIEW`;
export const NEW_PASSWORD_VIEW = `NEW_PASSWORD_VIEW`;
